import { useEffect, useMemo, useRef, useState } from 'react';
import html2canvas from 'html2canvas';
import { collection, doc, getDocs, increment, onSnapshot, runTransaction, setDoc, writeBatch } from 'firebase/firestore';
import { Copy, FilePlus2, ImageDown, Pencil, Plus, Printer, Search, Trash2 } from 'lucide-react';
import { firestore } from '@/lib/firebase';
import { Button } from '@/components/ui/button';
import { Card, CardContent } from '@/components/ui/card';

type Item = { rowId: string; productName: string; qty: number; price: number; gstRate: number };
type Invoice = { id: string; refNo: string; issueDate: string; payTerms: string; placeOfSupply: string; custName: string; custAddr: string; custPhone: string; custState: string; custGstin: string; items: Item[]; transport: number; advancePaid: number; taxRate?: number; savedAt?: string };
type Product = { name: string; price1?: number; price50?: number; price100?: number; gstRate?: number; stock?: number };
type Draft = Omit<Invoice, 'id' | 'savedAt'>;

const DEFAULT_PRODUCTS: Product[] = [
  ['2 Inch Pot',25,22,20,5], ['3 inch Pot',40,30,25,5], ['4 inch Pot',50,35,30,5], ['6 inch Pot Std',60,50,45,5], ['6 inch Pot Heavy',70,50,45,5], ['8 Inch Pot',80,60,50,5], ['Hangeer for 8 inch',150,140,120,5], ['50 mm Disc',15,12,10,5], ['100 mm Disc',0,0,0,5], ['650 Gm Bric',99,89,79,5], ['5Kg Block',300,269,249,5], ['Pole 1 Feet',0,0,0,5], ['Ready Pot',149,135,129,5], ['Starter Kit',159,145,139,5], ['Medium Kit',249,235,229,5], ['Premium Kit',699,659,649,5], ['Ready pot With Out Plant',130,119,99,5], ['Packing Box',100,100,100,0],
].map(([name, price1, price50, price100, gstRate]) => ({ name: String(name), price1: Number(price1), price50: Number(price50), price100: Number(price100), gstRate: Number(gstRate) }));
const today = () => new Date().toISOString().slice(0, 10);
const emptyItem = (): Item => ({ rowId: crypto.randomUUID(), productName: '', qty: 0, price: 0, gstRate: 5 });
const isPackingRow = (name: string) => name === 'Packing Box' || name === 'Packing';
const packingItem = (productsList: Product[] = []): Item => {
  const prod = productsList.find(p => p.name === 'Packing Box' || p.name === 'Packing');
  return { rowId: crypto.randomUUID(), productName: 'Packing Box', qty: 0, price: prod?.price1 ?? 100, gstRate: prod?.gstRate ?? 0 };
};
const emptyDraft = (productsList: Product[] = []): Draft => ({ refNo: '', issueDate: today(), payTerms: 'Immediate', placeOfSupply: 'Karnataka (29)', custName: '', custAddr: '', custPhone: '', custState: '', custGstin: '', items: [emptyItem(), packingItem(productsList)], transport: 0, advancePaid: 0, taxRate: 5 });
const n = (value: unknown) => Math.max(0, Number(value) || 0);
const money = (value: number) => `₹${value.toLocaleString('en-IN', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
const safeName = (value: string) => value.replace(/[^a-z0-9]+/gi, '_').replace(/^_|_$/g, '') || 'invoice';
function amountInWords(value: number) { const ones = ['','One','Two','Three','Four','Five','Six','Seven','Eight','Nine','Ten','Eleven','Twelve','Thirteen','Fourteen','Fifteen','Sixteen','Seventeen','Eighteen','Nineteen']; const tens = ['','','Twenty','Thirty','Forty','Fifty','Sixty','Seventy','Eighty','Ninety']; const say = (num: number): string => num < 20 ? ones[num] : num < 100 ? `${tens[Math.floor(num / 10)]}${num % 10 ? ` ${ones[num % 10]}` : ''}` : num < 1000 ? `${ones[Math.floor(num / 100)]} Hundred${num % 100 ? ` ${say(num % 100)}` : ''}` : num < 100000 ? `${say(Math.floor(num / 1000))} Thousand${num % 1000 ? ` ${say(num % 1000)}` : ''}` : num < 10000000 ? `${say(Math.floor(num / 100000))} Lakh${num % 100000 ? ` ${say(num % 100000)}` : ''}` : `${say(Math.floor(num / 10000000))} Crore${num % 10000000 ? ` ${say(num % 10000000)}` : ''}`; return `Rupees ${say(Math.round(value)) || 'Zero'} Only`; }

function isNonInventoryItem(name: string) {
  const s = String(name || '').trim().toLowerCase();
  return !s || /^packing(\b|\s|&|\+|-|_)/i.test(s) || s === 'packing' || /packing\s*(box|charges|charge|&|\+|and)?/i.test(s) || /^(handling|transport(ation)?|shipping|delivery|freight|courier)\s*(charges|charge)?/i.test(s) || ['packing & handling', 'packing and handling', 'packing + handling'].some((term) => s.includes(term));
}

function financialYear(date = new Date()) { const start = date.getMonth() < 3 ? date.getFullYear() - 1 : date.getFullYear(); return `${String(start).slice(-2)}-${String(start + 1).slice(-2)}`; }
function refPattern(fy: string) { return new RegExp(`^BB/${fy.replace('-', '\\-')}/(\\d+)$`, 'i'); }

export default function InvoiceWorkspace() {
  const [invoices, setInvoices] = useState<Invoice[]>([]);
  const [products, setProducts] = useState<Product[]>(DEFAULT_PRODUCTS);
  const [draft, setDraft] = useState<Draft>(emptyDraft);
  const [editingId, setEditingId] = useState<string | null>(null);
  const [query, setQuery] = useState('');
  const [notice, setNotice] = useState('');
  const [busy, setBusy] = useState(false);
  const [showForm, setShowForm] = useState(false);
  const previewRef = useRef<HTMLDivElement>(null);
  const role = sessionStorage.getItem('bb_admin_role') || 'admin';
  const canEdit = role !== 'viewer';

  const audit = async (action: string, entityId: string, summary: string, details: Record<string, unknown> = {}) => {
    const event = { timestamp: new Date().toISOString(), action, performedBy: sessionStorage.getItem('bb_admin_user') || 'admin', entityId, summary, details, userAgent: navigator.userAgent };
    await setDoc(doc(collection(firestore, 'audit_logs')), event);
    fetch('/api/audit-log', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(event) }).catch(() => undefined);
  };
  const catalogPrice = (product: Product, qty: number) => qty >= 100 && n(product.price100) ? n(product.price100) : qty >= 50 && n(product.price50) ? n(product.price50) : n(product.price1) || null;
  const inventoryQuantities = (items: Item[]) => items.reduce<Record<string, number>>((result, item) => { if (!isNonInventoryItem(item.productName) && n(item.qty)) result[item.productName] = (result[item.productName] || 0) + n(item.qty); return result; }, {});

  useEffect(() => {
    const unsubInvoices = onSnapshot(collection(firestore, 'invoices'), snapshot => setInvoices(snapshot.docs.map(row => ({ id: row.id, ...row.data() } as Invoice)).sort((a, b) => String(b.savedAt || '').localeCompare(String(a.savedAt || '')))));
    const unsubProducts = onSnapshot(collection(firestore, 'products'), snapshot => {
      if (snapshot.empty) {
        const batch = writeBatch(firestore); DEFAULT_PRODUCTS.forEach(product => batch.set(doc(firestore, 'products', product.name), product, { merge: true })); batch.commit().catch(() => undefined);
      } else setProducts(snapshot.docs.map(row => ({ name: row.id, ...row.data() } as Product)).sort((a, b) => a.name.localeCompare(b.name)));
    });
    const raw = localStorage.getItem('bb_invoices');
    if (!localStorage.getItem('bb_migrated_v1') && raw) {
      try { const legacy = JSON.parse(raw); const batch = writeBatch(firestore); if (Array.isArray(legacy)) legacy.forEach((invoice: Invoice) => invoice?.id && batch.set(doc(firestore, 'invoices', invoice.id), invoice, { merge: true })); batch.commit().then(() => localStorage.setItem('bb_migrated_v1', '1')).catch(() => undefined); } catch { localStorage.setItem('bb_migrated_v1', '1'); }
    }
    return () => { unsubInvoices(); unsubProducts(); };
  }, []);

  useEffect(() => { if (!draft.refNo && !editingId) suggestReference(); }, [products]);
  async function suggestReference() { const fy = financialYear(); const rows = await getDocs(collection(firestore, 'invoices')); const highest = rows.docs.reduce((max, row) => Math.max(max, Number(refPattern(fy).exec(String(row.data().refNo || ''))?.[1] || 0)), 0); setDraft(current => current.refNo ? current : { ...current, refNo: `BB/${fy}/${String(highest + 1).padStart(3, '0')}` }); }
  async function claimReference(reference: string) {
    const fy = financialYear(); const match = refPattern(fy).exec(reference.trim()); if (!match) return reference.trim();
    const next = await runTransaction(firestore, async transaction => { const counter = doc(firestore, 'counters', fy); const snap = await transaction.get(counter); const rows = await getDocs(collection(firestore, 'invoices')); const highest = rows.docs.reduce((max, row) => Math.max(max, Number(refPattern(fy).exec(String(row.data().refNo || ''))?.[1] || 0)), 0); const sequence = Math.max(Number(snap.data()?.seq || 0), highest, Number(match[1]) - 1) + 1; transaction.set(counter, { seq: sequence, updatedAt: new Date().toISOString() }, { merge: true }); return sequence; });
    return `BB/${fy}/${String(next).padStart(3, '0')}`;
  }
  const totals = useMemo(() => { const subtotal = draft.items.reduce((sum, item) => sum + n(item.qty) * n(item.price), 0); const tax = draft.items.reduce((sum, item) => sum + n(item.qty) * n(item.price) * n(item.gstRate) / 100, 0); const grand = subtotal + tax + n(draft.transport); return { subtotal, tax, grand, balance: Math.max(0, grand - n(draft.advancePaid)) }; }, [draft]);
  const filtered = useMemo(() => invoices.filter(invoice => `${invoice.refNo || ''} ${invoice.custName || ''} ${invoice.custPhone || ''}`.toLowerCase().includes(query.toLowerCase())), [invoices, query]);
  const changeDraft = (key: keyof Draft, value: string | number | Item[]) => setDraft(current => ({ ...current, [key]: value }));
  const updateItem = (rowId: string, patch: Partial<Item>) => setDraft(current => ({ ...current, items: current.items.map(item => item.rowId === rowId ? { ...item, ...patch } : item) }));
  const chooseProduct = (item: Item, name: string) => { const product = products.find(p => p.name === name); updateItem(item.rowId, { productName: name, price: product ? catalogPrice(product, item.qty) ?? item.price : item.price, gstRate: product?.gstRate ?? (isPackingRow(name) ? 0 : 5) }); };
  const changeQuantity = (item: Item, qty: number) => { const product = products.find(p => p.name === item.productName); updateItem(item.rowId, { qty, ...(product && catalogPrice(product, qty) ? { price: catalogPrice(product, qty)! } : {}) }); };
  const addItem = () => setDraft(current => ({ ...current, items: [...current.items.slice(0, -1), emptyItem(), current.items.at(-1) && isPackingRow(current.items.at(-1)!.productName) ? current.items.at(-1)! : packingItem(products)] }));
  const removeItem = (item: Item) => { if (isPackingRow(item.productName)) return; setDraft(current => { const items = current.items.filter(row => row.rowId !== item.rowId); return { ...current, items: items.filter(row => !isPackingRow(row.productName)).length ? items : [emptyItem(), packingItem(products)] }; }); };
  const addCustomProduct = async () => { const name = window.prompt('Custom product name'); if (!name?.trim()) return; const product: Product = { name: name.trim(), price1: 0, price50: 0, price100: 0, gstRate: 5, stock: 0 }; await setDoc(doc(firestore, 'products', product.name), product, { merge: true }); setNotice(`${product.name} added to the catalog.`); };

  async function saveInvoice() {
    if (!canEdit) return; if (!draft.refNo.trim()) { setNotice('Invoice reference is required.'); return; }
    if (draft.items.some(item => !Number.isFinite(n(item.qty)) || !Number.isFinite(n(item.price)))) { setNotice('Enter valid quantities and prices.'); return; }
    setBusy(true); try {
      const existing = editingId ? invoices.find(invoice => invoice.id === editingId) : undefined;
      const refNo = existing ? draft.refNo.trim() : await claimReference(draft.refNo);
      const id = editingId || `INV-${Date.now()}`;
      const invoice: Invoice = { ...draft, id, refNo, items: draft.items.map(item => ({ ...item, qty: n(item.qty), price: n(item.price), gstRate: n(item.gstRate) })), transport: n(draft.transport), advancePaid: n(draft.advancePaid), savedAt: new Date().toISOString() };
      const oldQty = inventoryQuantities(existing?.items || []); const newQty = inventoryQuantities(invoice.items); const names = new Set([...Object.keys(oldQty), ...Object.keys(newQty)]); const batch = writeBatch(firestore);
      names.forEach(name => { const delta = (newQty[name] || 0) - (oldQty[name] || 0); if (delta) batch.set(doc(firestore, 'products', name), { stock: increment(-delta), lastUpdated: new Date().toISOString() }, { merge: true }); });
      batch.set(doc(firestore, 'invoices', id), invoice); await batch.commit();
      await audit(existing ? 'INVOICE_UPDATE' : 'INVOICE_CREATE', id, `${existing ? 'Updated' : 'Created'} invoice ${refNo}`, { refNo, customer: invoice.custName, grandTotal: totals.grand, stockDelta: [...names].reduce<Record<string, number>>((result, name) => ({ ...result, [name]: (newQty[name] || 0) - (oldQty[name] || 0) }), {}) });
      setDraft({ ...invoice }); setEditingId(id); setNotice(`Invoice ${refNo} saved.`);
    } catch (error) { setNotice(error instanceof Error ? error.message : 'Could not save the invoice.'); } finally { setBusy(false); }
  }
  function editInvoice(invoice: Invoice, duplicate = false) { const items = (invoice.items || []).map(item => ({ ...item, rowId: crypto.randomUUID(), gstRate: n(item.gstRate ?? invoice.taxRate ?? 5) })); const normalized = items.some(item => isPackingRow(item.productName)) ? items : [...items, packingItem(products)]; setDraft({ ...emptyDraft(products), ...invoice, issueDate: duplicate ? today() : invoice.issueDate || today(), refNo: duplicate ? '' : invoice.refNo, items: normalized }); setEditingId(duplicate ? null : invoice.id); setShowForm(true); if (duplicate) setTimeout(suggestReference, 0); }
  async function deleteInvoice(invoice: Invoice) { if (!canEdit || !window.confirm(`Delete ${invoice.refNo}? Stock will be restored.`)) return; setBusy(true); try { const batch = writeBatch(firestore); Object.entries(inventoryQuantities(invoice.items || [])).forEach(([name, qty]) => batch.set(doc(firestore, 'products', name), { stock: increment(qty), lastUpdated: new Date().toISOString() }, { merge: true })); batch.delete(doc(firestore, 'invoices', invoice.id)); await batch.commit(); await audit('INVOICE_DELETE', invoice.id, `Deleted invoice ${invoice.refNo}`, { refNo: invoice.refNo, restoredStock: inventoryQuantities(invoice.items || []) }); setNotice(`Deleted ${invoice.refNo}; stock restored.`); if (editingId === invoice.id) startNew(); } catch { setNotice('Could not delete the invoice.'); } finally { setBusy(false); } }
  function startNew() { setEditingId(null); setDraft(emptyDraft(products)); setShowForm(true); setTimeout(suggestReference, 0); }
  async function exportImage() { await saveInvoice(); if (!previewRef.current) return; const canvas = await html2canvas(previewRef.current, { scale: 2.5, backgroundColor: '#ffffff', useCORS: true }); const anchor = document.createElement('a'); anchor.download = `${safeName(draft.refNo)}_${safeName(draft.custName)}.png`; anchor.href = canvas.toDataURL('image/png'); anchor.click(); }
  async function printInvoice() { await saveInvoice(); const before = document.title; document.title = `${safeName(draft.refNo)}_${safeName(draft.custName)}`; window.print(); document.title = before; }

  return (
    <div className="mx-auto max-w-7xl space-y-5">
      <div className="no-print rounded-2xl border border-[#e8d7ba] bg-[#fcf7ee] p-4 sm:p-5 shadow-sm flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4">
        <div>
          <div className="flex items-center gap-2.5">
            <h1 className="text-xl sm:text-2xl font-extrabold text-slate-900 font-display">Invoices &amp; Billing</h1>
            <span className="rounded-full bg-emerald-100 px-2.5 py-0.5 text-xs font-bold text-emerald-800">
              {invoices.length} {invoices.length === 1 ? 'Invoice' : 'Invoices'}
            </span>
          </div>
          <p className="text-xs sm:text-sm text-slate-600 mt-1">
            Create, edit, duplicate, export, and audit live commercial tax invoices.
          </p>
        </div>
        <Button size="default" className="bg-[#031c0e] hover:bg-emerald-950 text-white rounded-xl shadow-sm font-bold" onClick={startNew} disabled={!canEdit}>
          <FilePlus2 className="h-4 w-4 mr-1.5" /> New invoice
        </Button>
      </div>
      {notice && <p className="no-print rounded-xl border border-brand-200 bg-brand-50 px-4 py-3 text-sm text-brand-900">{notice}</p>}
      {showForm && <div className="no-print grid gap-6 xl:grid-cols-[minmax(0,1fr)_340px]"><Card><CardContent className="p-5 sm:p-7"><div className="flex items-center justify-between"><h2 className="text-xl font-bold text-slate-900">{editingId ? `Edit ${draft.refNo}` : 'New invoice'}</h2><Button variant="ghost" onClick={() => setShowForm(false)}>Close</Button></div><div className="mt-5 grid gap-4 md:grid-cols-3">{([['refNo','Invoice reference'],['issueDate','Issue date'],['payTerms','Payment terms'],['custName','Customer name'],['custPhone','Phone'],['custGstin','GSTIN'],['custAddr','Address'],['custState','Customer state'],['placeOfSupply','Place of supply']] as [keyof Draft,string][]).map(([key,label]) => <label key={String(key)} className="text-xs font-bold uppercase tracking-wide text-slate-500">{label}<input disabled={!canEdit} type={key === 'issueDate' ? 'date' : 'text'} value={String(draft[key] ?? '')} onChange={event => changeDraft(key, event.target.value)} className="mt-1.5 h-10 w-full rounded-lg border border-slate-200 px-3 text-sm font-normal text-slate-800 outline-none focus:border-brand-600 disabled:bg-slate-50" /></label>)}</div>
        <div className="mt-7 flex items-center justify-between"><h3 className="font-bold text-slate-900">Items</h3><div className="flex gap-2"><Button size="sm" variant="outline" onClick={addCustomProduct} disabled={!canEdit}>Add catalog item</Button><Button size="sm" onClick={addItem} disabled={!canEdit}><Plus className="h-4 w-4" /> Item</Button></div></div><div className="mt-3 overflow-x-auto"><table className="min-w-[730px] w-full text-sm"><thead className="bg-slate-50 text-left text-xs uppercase text-slate-500"><tr><th className="p-3">Product</th><th className="p-3">Qty</th><th className="p-3">Price</th><th className="p-3">GST</th><th className="p-3">Amount</th><th className="p-3" /></tr></thead><tbody>{draft.items.map(item => <tr key={item.rowId} className="border-b border-slate-100"><td className="p-2"><input list="invoice-products" disabled={!canEdit || isPackingRow(item.productName)} value={item.productName} onChange={event => chooseProduct(item, event.target.value)} className="h-9 w-full rounded border border-slate-200 px-2" placeholder="Choose or type product" /></td><td className="p-2"><input disabled={!canEdit} min="0" type="number" value={item.qty || ''} onChange={event => changeQuantity(item, n(event.target.value))} className="h-9 w-20 rounded border border-slate-200 px-2" /></td><td className="p-2"><input disabled={!canEdit} min="0" type="number" value={item.price || ''} onChange={event => updateItem(item.rowId, { price: n(event.target.value) })} className="h-9 w-24 rounded border border-slate-200 px-2" /></td><td className="p-2"><select disabled={!canEdit} value={item.gstRate} onChange={event => updateItem(item.rowId, { gstRate: n(event.target.value) })} className="h-9 rounded border border-slate-200 px-2">{[0,5,12,18].map(rate => <option key={rate} value={rate}>{rate}%</option>)}</select></td><td className="p-2 font-semibold">{money(n(item.qty) * n(item.price))}</td><td className="p-2">{!isPackingRow(item.productName) && <button disabled={!canEdit} onClick={() => removeItem(item)} className="rounded p-2 text-red-500 hover:bg-red-50"><Trash2 className="h-4 w-4" /></button>}</td></tr>)}</tbody></table><datalist id="invoice-products">{products.map(product => <option key={product.name} value={product.name} />)}</datalist></div>
        <div className="mt-5 grid gap-4 sm:grid-cols-2"><label className="text-sm font-semibold">Transport<input disabled={!canEdit} type="number" min="0" value={draft.transport || ''} onChange={event => changeDraft('transport', n(event.target.value))} className="mt-1 h-10 w-full rounded border border-slate-200 px-3" /></label><label className="text-sm font-semibold">Advance paid<input disabled={!canEdit} type="number" min="0" value={draft.advancePaid || ''} onChange={event => changeDraft('advancePaid', n(event.target.value))} className="mt-1 h-10 w-full rounded border border-slate-200 px-3" /></label></div><div className="mt-6 flex flex-wrap gap-3"><Button onClick={saveInvoice} disabled={!canEdit || busy}>{busy ? 'Saving…' : 'Save invoice'}</Button><Button variant="outline" onClick={() => editInvoice({ ...draft, id: editingId || 'preview' }, true)} disabled={!canEdit}><Copy className="h-4 w-4" /> Duplicate as new</Button><Button variant="outline" onClick={printInvoice} disabled={!canEdit}><Printer className="h-4 w-4" /> Print / PDF</Button><Button variant="outline" onClick={exportImage} disabled={!canEdit}><ImageDown className="h-4 w-4" /> PNG</Button></div></CardContent></Card>
      <Card><CardContent className="p-6"><h3 className="font-bold text-slate-900">Invoice totals</h3><dl className="mt-4 space-y-3 text-sm"><div className="flex justify-between"><dt>Taxable value</dt><dd>{money(totals.subtotal)}</dd></div><div className="flex justify-between"><dt>GST</dt><dd>{money(totals.tax)}</dd></div><div className="flex justify-between"><dt>Transport</dt><dd>{money(n(draft.transport))}</dd></div><div className="flex justify-between border-t pt-3 text-base font-bold"><dt>Grand total</dt><dd>{money(totals.grand)}</dd></div><div className="flex justify-between"><dt>Advance paid</dt><dd>{money(n(draft.advancePaid))}</dd></div><div className="flex justify-between font-bold text-brand-800"><dt>Balance due</dt><dd>{money(totals.balance)}</dd></div></dl></CardContent></Card></div>}
    <Card className="no-print"><CardContent className="p-4"><label className="relative block"><Search className="pointer-events-none absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400" /><input value={query} onChange={event => setQuery(event.target.value)} className="h-11 w-full rounded-xl border border-slate-200 pl-10 pr-4" placeholder="Search invoice, customer, or phone" /></label></CardContent></Card><Card className="no-print overflow-hidden"><div className="overflow-x-auto"><table className="min-w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="px-5 py-4">Invoice</th><th className="px-5 py-4">Customer</th><th className="px-5 py-4">Date</th><th className="px-5 py-4">Total</th><th className="px-5 py-4">Actions</th></tr></thead><tbody>{filtered.map(invoice => { const total = (invoice.items || []).reduce((sum, item) => sum + n(item.qty) * n(item.price) * (1 + n(item.gstRate ?? invoice.taxRate ?? 5) / 100), 0) + n(invoice.transport); return <tr key={invoice.id} className="border-t border-slate-100"><td className="px-5 py-4 font-bold text-brand-800">{invoice.refNo || invoice.id}</td><td className="px-5 py-4">{invoice.custName || '—'}</td><td className="px-5 py-4">{invoice.issueDate || '—'}</td><td className="px-5 py-4 font-semibold">{money(total)}</td><td className="flex gap-1 px-5 py-3"><button onClick={() => editInvoice(invoice)} className="rounded p-2 hover:bg-slate-100"><Pencil className="h-4 w-4" /></button><button onClick={() => editInvoice(invoice, true)} className="rounded p-2 hover:bg-slate-100"><Copy className="h-4 w-4" /></button><button disabled={!canEdit} onClick={() => deleteInvoice(invoice)} className="rounded p-2 text-red-600 hover:bg-red-50"><Trash2 className="h-4 w-4" /></button></td></tr>; })}</tbody></table></div>{!filtered.length && <p className="p-10 text-center text-sm text-slate-500">No invoices found.</p>}</Card>
    {showForm && <div ref={previewRef} className="invoice-document">
      <div className="invoice-stripe" />
      <header className="invoice-header"><div><div className="invoice-company-name">Konaseema Coco Products LLP</div><div className="invoice-company-address">No 12, Ground Floor, AVP Complex, Sy No 97,<br />Dommasandra Village, Virgo Nagar Post,<br />Bangalore, Karnataka - 560049<br /><strong>GSTIN: 29ABGFK2654K1ZX</strong><br />+91 8951744898 · info@brickbloom.co.in<br />brickbloom.co.in</div></div><img src="/images/OurProducts/Logo_new.jpeg" alt="BrickBloom" className="invoice-company-logo" /><div className="invoice-header-right"><div className="invoice-tax-tag">TAX INVOICE</div><div className="invoice-original">Original for Recipient</div><div className="invoice-detail"><span>Invoice No:</span><strong className="invoice-reference">{draft.refNo || 'BB/--/---'}</strong></div><div className="invoice-detail"><span>Date:</span><strong>{draft.issueDate}</strong></div><div className="invoice-detail"><span>Payment Mode:</span><strong>{draft.payTerms}</strong></div><div className="invoice-detail"><span>Place of Supply:</span><strong>{draft.placeOfSupply}</strong></div></div></header>
      <section className="invoice-parties"><div className="invoice-party"><div className="invoice-label">Bill To</div><div className="invoice-buyer">{draft.custName || 'Customer Name'}</div><div className="invoice-small">{draft.custAddr || '—'}<br />{draft.custState && <>State: <strong>{draft.custState}</strong><br /></>}{draft.custPhone && <>Phone: <strong>{draft.custPhone}</strong><br /></>}{draft.custGstin && <>GSTIN: <strong>{draft.custGstin}</strong></>}</div></div><div className="invoice-party"><div className="invoice-label">Dispatch Details</div><div className="invoice-small">Dispatched from: <strong>Bangalore, Karnataka</strong><br />Transport Charges: <strong>{money(n(draft.transport))}</strong></div></div></section>
      <section className="invoice-items"><div className="invoice-items-title">Description of Goods &amp; Services</div><table className="invoice-table"><colgroup><col style={{ width: '4%' }} /><col style={{ width: '32%' }} /><col style={{ width: '9%' }} /><col style={{ width: '12%' }} /><col style={{ width: '14%' }} /><col style={{ width: '14%' }} /><col style={{ width: '15%' }} /></colgroup><thead><tr><th>#</th><th>Item / Description</th><th>Qty</th><th>Rate (₹)</th><th>Taxable Amt</th><th>GST Amt</th><th>Total (₹)</th></tr></thead><tbody>{draft.items.filter(item => item.productName || item.qty).map((item, index) => { const taxable = n(item.qty) * n(item.price); const tax = taxable * n(item.gstRate) / 100; return <tr key={item.rowId}><td>{index + 1}</td><td><strong>{item.productName || '—'}</strong></td><td>{item.qty}</td><td>{money(n(item.price))}</td><td>{money(taxable)}</td><td>{item.gstRate ? `${money(tax)} (${item.gstRate}%)` : 'Exempt'}</td><td>{money(taxable + tax)}</td></tr>; })}<tr className="invoice-total-row"><td /><td>TOTAL</td><td>{draft.items.reduce((sum, item) => sum + n(item.qty), 0)}</td><td /><td>{money(totals.subtotal)}</td><td>{money(totals.tax)}</td><td>{money(totals.subtotal + totals.tax)}</td></tr></tbody></table></section>
      <section className="invoice-financials"><div className="invoice-words"><div className="invoice-section-label">Amount in Words</div><p>{amountInWords(totals.grand)}</p></div><div className="invoice-summary"><div className="invoice-summary-row"><span>Taxable Value</span><strong>{money(totals.subtotal)}</strong></div>{[...new Set(draft.items.map(item => n(item.gstRate)).filter(Boolean))].sort((a,b) => a-b).map(rate => { const tax = draft.items.filter(item => n(item.gstRate) === rate).reduce((sum, item) => sum + n(item.qty) * n(item.price) * rate / 100, 0); return <div key={rate}><div className="invoice-summary-row"><span>CGST @ {rate / 2}%</span><strong>{money(tax / 2)}</strong></div><div className="invoice-summary-row"><span>SGST @ {rate / 2}%</span><strong>{money(tax / 2)}</strong></div></div>; })}<div className="invoice-summary-row"><span>Transport</span><strong>{money(n(draft.transport))}</strong></div><div className="invoice-grand"><span>Total Payable</span><span>{money(totals.grand)}</span></div>{n(draft.advancePaid) > 0 && <><div className="invoice-summary-row"><span>Advance Paid</span><strong>− {money(n(draft.advancePaid))}</strong></div><div className="invoice-balance"><span>Balance Due</span><span>{money(totals.balance)}</span></div></>}</div></section>
      <footer className="invoice-footer"><div className="invoice-terms"><strong>Terms &amp; Conditions:</strong><br />1. Goods once dispatched are non-returnable without prior written consent. 2. Interest @ 18% p.a. applies on payments overdue beyond agreed terms. 3. All disputes subject to Bangalore jurisdiction only.</div><div className="invoice-signature">For Konaseema Coco Products LLP<img src="/images/konaseema_seal.jpg" alt="Company seal" className="invoice-seal" /><div className="invoice-sign-line">Authorised Signatory</div></div></footer><div className="invoice-tagline">🌱 Thank you for your business — BrickBloom: Sustainable Cocopeat Growing Media</div>
    </div>}
    </div>
  );
}
