import { useEffect, useState } from 'react';
import { LoaderCircle, LogOut, MessageCircle, Send } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';

type Status = 'disconnected' | 'initializing' | 'qr' | 'ready';

export default function WhatsAppWorkspace() {
  const [status, setStatus] = useState<Status>('disconnected'); const [error, setError] = useState(''); const [phone, setPhone] = useState(''); const [message, setMessage] = useState('');
  const refresh = async () => { try { const response = await fetch('/api/wa/status'); const data = await response.json(); setStatus(data.status || 'disconnected'); setError(data.error || ''); } catch { setError('Start the local BrickBloom server to use WhatsApp.'); } };
  useEffect(() => { void refresh(); const timer = window.setInterval(() => void refresh(), 5000); return () => window.clearInterval(timer); }, []);
  const connect = async () => { setError(''); await fetch('/api/wa/connect', { method: 'POST' }); await refresh(); };
  const disconnect = async () => { await fetch('/api/wa/disconnect', { method: 'POST' }); await refresh(); };
  const send = async (event: React.FormEvent) => { event.preventDefault(); if (!phone || !message) return; const response = await fetch('/api/wa/send', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ contacts: [{ name: 'Customer', phone }], template: message }) }); if (!response.ok) setError('Message could not be sent. Confirm the WhatsApp session is connected.'); else { setMessage(''); setPhone(''); } };
  const connected = status === 'ready';
  return <div className="mx-auto max-w-4xl"><p className="eyebrow">Customer communication</p><h1 className="mt-3 text-4xl text-slate-900">WhatsApp</h1><p className="mt-2 text-slate-500">Connect your existing local WhatsApp service and send customer messages from the shared workspace.</p><div className="mt-8 grid gap-5 md:grid-cols-[0.85fr_1.15fr]"><Card><CardHeader><div className={`flex h-11 w-11 items-center justify-center rounded-xl ${connected ? 'bg-emerald-100 text-emerald-700' : 'bg-slate-100 text-slate-600'}`}><MessageCircle className="h-5 w-5" /></div><CardTitle className="mt-4">Session status</CardTitle><CardDescription>{connected ? 'Connected and ready to send.' : status === 'initializing' || status === 'qr' ? 'Connection is in progress.' : 'No active WhatsApp session.'}</CardDescription></CardHeader><CardContent>{connected ? <Button variant="outline" onClick={disconnect}><LogOut className="h-4 w-4" /> Disconnect</Button> : <Button onClick={connect} disabled={status === 'initializing'}>{status === 'initializing' && <LoaderCircle className="h-4 w-4 animate-spin" />} Connect WhatsApp</Button>}{error && <p className="mt-4 text-sm text-red-600">{error}</p>}</CardContent></Card><Card><CardHeader><CardTitle>Send a message</CardTitle><CardDescription>Send one customer message through the connected local session.</CardDescription></CardHeader><CardContent><form onSubmit={send} className="space-y-4"><label className="block text-sm font-semibold text-slate-700">Phone number<input disabled={!connected} value={phone} onChange={(event) => setPhone(event.target.value)} className="mt-2 h-11 w-full rounded-xl border border-slate-200 px-3 font-normal outline-none focus:border-brand-600 disabled:bg-slate-50" placeholder="919876543210" /></label><label className="block text-sm font-semibold text-slate-700">Message<textarea disabled={!connected} value={message} onChange={(event) => setMessage(event.target.value)} className="mt-2 min-h-28 w-full rounded-xl border border-slate-200 p-3 font-normal outline-none focus:border-brand-600 disabled:bg-slate-50" placeholder="Hello, thank you for choosing BrickBloom." /></label><Button type="submit" disabled={!connected}><Send className="h-4 w-4" /> Send message</Button></form></CardContent></Card></div></div>;
}
